version: '3'
networks:
  mynetwork:
    name: mynetwork
services:
  db:
    image: mysql:8.0
    container_name: db_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootasdf1234
      MYSQL_DATABASE: db_site1
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  wordpress_mainsite:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wp_main_site
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: rootasdf1234
      WORDPRESS_DB_NAME: db_site1
    volumes:
      - ./wordpress_main_data/wp-content:/var/www/html/wp-content
    networks:
      - mynetwork
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_mainsite
    restart: always
    ports:
      - 8082:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootasdf1234
    networks:
      - mynetwork

volumes:
  db_data:
  wordpress_main_data: